service: graphql-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  graphql:
    handler: dist/index.handler
    events:
      - http:
          path: graphql
          method: post
